---
- name: Kubernetes Deployment
  hosts: all
    # become: true
  tasks:
  - name: delete old namespace
    command: kubectl delete -f /home/ubuntu/namespace.yaml
  - name: delete old deployment
    command: kubectl delete -f /home/ubuntu/deployment.yml
  - name: delete old service
    command: kubectl delete -f /home/ubuntu/service.yaml
  - name: create new namespace
    command: kubectl apply -f /home/ubuntu/namespace.yaml
  - name: create new deployment
    command: kubectl apply -f /home/ubuntu/deployment.yml
  - name: create new service
    command: kubectl apply -f /home/ubuntu/service.yaml 
