apiVersion: v1
kind: Service
metadata:
  name: k8s-project1-service
  namespace: app

spec:
  type: LoadBalancer
  selector:
    app: k8s-project1

  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP